### ISSUE TITLE
Compounds crash wolves

### ISSUE THREAD

**Issue by DaemonUmbra** [al132mc/chem-lib#3] opened 2022-03-09 23:50 UTC
Due to CompoundItems lacking FoodProperties while returning true in isEdible, the isFood method in WolfEntity will crash with a NullPointerException whenever a player in begging range is holding a compound

**Comment by ghost** [comment] 2022-03-19 21:20
This is pretty niche, but I confirmed it. It only happens when the compound is one that can be consumed. Fixed in 1.16.5-2. It was a non-issue in 1.18 because of changes made in the port.

**Closed as completed by ghost** 2022-03-19 21:20 UTC
